### ISSUE TITLE
Щас школота налетит

### ISSUE THREAD

**Issue by MCausc78** [Sempai-07/aoitelegram#6]
Аои говно как и бдфд (Python подтверждает)

**Comment by Sempai-07** [comment]
У меня нет ничего против твоего мнения, особенно по поводу `aoijs v6`, которое не нравится тебе, а bdfd просто донатная помойка. Но сравнивать целый язык с `aoijs` (которая является библиотекой в большой степени) очень гениально, я так скажу 👀

**Comment by im-Albania** [comment]
> Аои говно как и бдфд (Python подтверждает)

Клоун

**Comment by im-Albania** [comment]
> Аои говно как и бдфд (Python подтверждает)

Пасаси гавна, если не можешь освоить бдфд с аоем то тебе явно рано в айти

**Comment by MCausc78** [comment]
> > Аои говно как и бдфд (Python подтверждает)
> 
> Пасаси гавна, если не можешь освоить бдфд с аоем то тебе явно рано в айти

Давно осилил, и вообще-то у меня есть своя [библиотека](https://github.com/DarpHome/discord.v)
Между прочем подобные библиотеки - это гребанные обёртки над discord.js/disnake и все. Очень смешно

**Comment by Sempai-07** [comment]
> > > Аои говно как и бдфд (Python подтверждает)
> > 
> > 
> > Пасаси гавна, если не можешь освоить бдфд с аоем то тебе явно рано в айти
> 
> Давно осилил, и вообще-то у меня есть своя [библиотека](https://github.com/DarpHome/discord.v) Между прочем подобные библиотеки - это гребанные обёртки над discord.js/disnake и все. Очень смешно

Разницы нет в том, на чем писать, если речь идет о взаимодействии с API. Каждый выбирает то, что лучше соответствует его возможностям и задачам. Тупо - просто послать челика потому-что тебе не понравилось его мнение 👀

**Comment by Sempai-07** [comment]
Та и школота здесь только ты, нормальный человек не написал бы такое. И брать отмазки о том, что ты хочешь помочь людям, чтобы они писали на чистом (не на обёртках) NodeJS — бред. Библиотека (обёртка) создана для упрощения жизни человека, не так ли?

**Comment by MCausc78** [comment]
> Та и школота здесь только ты, нормальный человек не написал бы такое. И брать отмазки о том, что ты хочешь помочь людям, чтобы они писали на чистом (не на обёртках) NodeJS — бред. Библиотека (обёртка) создана для упрощения жизни человека, не так ли?

Нормальный человек максимально обосрет подобную хрень, а школота и вправду пишет на бдфд/аои. Иди взгляни на их комьюнити, она обосрет Node.js и Python из-за того что "слажнааа". И опять же - код в строке это плохая идея, очень ненадежно и из-за этого может возникнуть кучу ошибок о правильном синтаксисе из-за плохого парсера/лексера. Ну и гибкости очень мало

**Comment by Sempai-07** [comment]
> > Та и школота здесь только ты, нормальный человек не написал бы такое. И брать отмазки о том, что ты хочешь помочь людям, чтобы они писали на чистом (не на обёртках) NodeJS — бред. Библиотека (обёртка) создана для упрощения жизни человека, не так ли?
> 
> Нормальный человек максимально обосрет подобную хрень, а школота и вправду пишет на бдфд/аои. Иди взгляни на их комьюнити, она обосрет Node.js и Python из-за того что "слажнааа". И опять же - код в строке это плохая идея, очень ненадежно и из-за этого может возникнуть кучу ошибок о правильном синтаксисе из-за плохого парсера/лексера. Ну и гибкости очень мало

Разумеется, у каждого свой взгляд на вещи. Некоторые предпочитают более сложные языки и библиотеки, а другие выбирают простоту и удобство. Комьюнити бдфд - да, они очень странные, но бдфд комьюнити на офф сервере не говорили не разу, что js/py - сложные они наоборот говорят что лучше писать ботов, если брать не бдфд - это py. А аой комьюнити вообще пишут на js, я никогда не выдел чтобы они сказали на js гомно - поэтому то что ты написал это твои фантазии. Та и что за бред "код в строке это плохая идея" - все языки программирования спроектированы так, чтобы разобрать файл - а содержимое файла в первую очередь это сплошная строка которою лексер и парсер разобрать должны. Синтаксис `$` и `[]` это изюминка пакета, если ты против это не значить, что все против 😕

**Comment by Sempai-07** [comment]
> > Та и школота здесь только ты, нормальный человек не написал бы такое. И брать отмазки о том, что ты хочешь помочь людям, чтобы они писали на чистом (не на обёртках) NodeJS — бред. Библиотека (обёртка) создана для упрощения жизни человека, не так ли?
> 
> Нормальный человек максимально обосрет подобную хрень, а школота и вправду пишет на бдфд/аои. Иди взгляни на их комьюнити, она обосрет Node.js и Python из-за того что "слажнааа". И опять же - код в строке это плохая идея, очень ненадежно и из-за этого может возникнуть кучу ошибок о правильном синтаксисе из-за плохого парсера/лексера. Ну и гибкости очень мало

Разумеется, у каждого свой взгляд на вещи. Некоторые предпочитают более сложные языки и библиотеки, а другие выбирают простоту и удобство. Комьюнити бдфд - да, они очень странные, но бдфд комьюнити на офф сервере не говорили не разу, что js/py - сложные они наоборот говорят что лучше писать ботов, если брать не бдфд - это py. А аой комьюнити вообще пишут на js, я никогда не выдел чтобы они сказали на js гомно - поэтому то что ты написал это твои фантазии. Та и что за бред "код в строке это плохая идея" - все языки программирования спроектированы так, чтобы разобрать файл - а содержимое файла в первую очередь это сплошная строка которою лексер и парсер разобрать должны. Синтаксис `$` и `[]` это изюминка пакета, если ты против это не значить, что все против 😕

**Comment by Sempai-07** [comment]
Ну в принципе, всё понятно с тобой. Ты вылез из леса, показал, какой ты "умный", похвастался своей "популярной" библиотекой на нн ЯП который на Rust и Go похож, и ушёл. Я даже нормального обсёра не увыдел. Вечно выдумки про комьюнити bdfd/aoi — комьюнити других библиотек и ЯП также несут бред про другие языки, что они сложные и нечитабельные, но в то же время их используют. Я закрою данный `Issues`, если не напишешь через 10 часов нормальный пруф, а не как сейчас тыкаешь пальцем в воздух. 🤷‍♂️

**Comment by MCausc78** [comment]
Пишет тот кто сам пишет на бдфд/аои💀

**Comment by Sempai-07** [comment]
Хаха, я говорю, пруфов ноль. Я на DBFD и AOI года два не пишу, соответственно, высер с воздуха, как я и говорил в прошлых сообщениях. Также на мои предыдущие сообщение ты ничего не смог сказать, и тут у меня сомнения, кто из нас ребёнок. В следующий раз хотя бы выучи и напиши популярную библиотеку на нормальном языке, а не как сейчас написал нн библиотеку на нн яп и ходишь по GitHub, говоришь, что наши библиотеки полное гомно. Так ещё такие глупие пруфы. Ты вообще чем учишь языки программирования, случаем, не жопой? Удачи, малыш.

**Comment by FeroxNotFriday** [comment]
дети срутся шок

**Comment by FeroxNotFriday** [comment]
> Пишет тот кто сам пишет на бдфд/аои💀

Я тебе больше скажу: на аои создан бот, который сложнее любого другого на том же диснейке, и сделал его именно я)

**Comment by Sempai-07** [comment]
Можеш не писать сюда, он в блоке

**Comment by FeroxNotFriday** [comment]
Разблочь ребёнка

**Comment by Sempai-07** [comment]
Ради тебя окей

**Comment by FeroxNotFriday** [comment]
И как то тупо сравнивать библиотеку и язык)

**Comment by FeroxNotFriday** [comment]
Ради вас на гит зашёл

**Comment by Sempai-07** [comment]
@MCausc78

**Comment by FeroxNotFriday** [comment]
Поржать с ваших остроумных мыслей

**Comment by Sempai-07** [comment]
> И как то тупо сравнивать библиотеку и язык)

Я это в самом начале говорил

**Comment by FeroxNotFriday** [comment]
На диснейке даже селфа нет кста

**Comment by FeroxNotFriday** [comment]
Лошня

**Comment by MCausc78** [comment]
> На диснейке даже селфа нет кста

Там можно HTTPClient.request подменить + селфы идут против тоса

**Comment by Sempai-07** [comment]
> На диснейке даже селфа нет кста

Так пайтон на всё способен 🙄

**Comment by MCausc78** [comment]
Ффи курит

**Comment by FeroxNotFriday** [comment]
> > На диснейке даже селфа нет кста
> 
> Так пайтон на всё способен 🙄

Калькулятор максимум запустить

**Comment by FeroxNotFriday** [comment]
Как язык он слабый и медленный

**Comment by MCausc78** [comment]
> Как язык он слабый и медленный

Прикладывай пруфы

**Comment by FeroxNotFriday** [comment]
Сравнивая с теми же плюсами и растом)

**Comment by FeroxNotFriday** [comment]
Он ничтожный

**Comment by MCausc78** [comment]
А ты скомпилируй его нуиткой или ситоном вот и будет быстрее

**Comment by FeroxNotFriday** [comment]
Дс свой дай, в этом говне общаться невозможно

**Comment by MCausc78** [comment]
nerdarp

**Comment by MCausc78** [comment]
Держи

**Comment by FeroxNotFriday** [comment]
А

**Comment by FeroxNotFriday** [comment]
Тот самый тру ассемблер дев?)

**Comment by FeroxNotFriday** [comment]
Мне кажется разработчики ассемблера не будут ради питона упираться

**Comment by FeroxNotFriday** [comment]
> А ты скомпилируй его нуиткой или ситоном вот и будет быстрее

Смысл мне что-то делать, чтобы выкручиваться? Я получил готовый инструмент, так пусть он сам делает что мне надо. Уж тогда и правда на двоичной хуйне сидеть дрочиться, сигналы посылать

**Comment by FeroxNotFriday** [comment]
> > Та и школота здесь только ты, нормальный человек не написал бы такое. И брать отмазки о том, что ты хочешь помочь людям, чтобы они писали на чистом (не на обёртках) NodeJS — бред. Библиотека (обёртка) создана для упрощения жизни человека, не так ли?
> 
> Нормальный человек максимально обосрет подобную хрень, а школота и вправду пишет на бдфд/аои. Иди взгляни на их комьюнити, она обосрет Node.js и Python из-за того что "слажнааа". И опять же - код в строке это плохая идея, очень ненадежно и из-за этого может возникнуть кучу ошибок о правильном синтаксисе из-за плохого парсера/лексера. Ну и гибкости очень мало

Я комьюнити аои. Сижу и на том же джс, срайтоне и слоне пишу

**Comment by MCausc78** [comment]
> Мне кажется разработчики ассемблера не будут ради питона упираться

Мне лень стало что то писать на ассемблере

**Comment by FeroxNotFriday** [comment]
Ну или ты не осилил. Будем честны

**Comment by MCausc78** [comment]
> Ну или ты не осилил. Будем честны

А я че должен искать UV с SSL?

**Comment by FeroxNotFriday** [comment]
> > > Аои говно как и бдфд (Python подтверждает)
> > 
> > 
> > Пасаси гавна, если не можешь освоить бдфд с аоем то тебе явно рано в айти
> 
> Давно осилил, и вообще-то у меня есть своя [библиотека](https://github.com/DarpHome/discord.v) Между прочем подобные библиотеки - это гребанные обёртки над discord.js/disnake и все. Очень смешно

Питон тоже обёртка, и диснейк также обёртка обёртки

**Comment by FeroxNotFriday** [comment]
Так что у тебя логика по сути позорная

**Comment by FeroxNotFriday** [comment]
terronofficial заявку кинь, потрещим
